routes/admin.php
<?php

Route::group(['prefix' => 'admin',  'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::get('', 'Auth\LoginController@showLoginForm');
});

/* Required auth and permission middleware */
Route::group(['middleware' => ['auth', 'permission'],'prefix'=>'admin','namespace'=>"Admin"], function () {

    /*General settings */
    Route::get('settings', 'UserController@showSetting')->name('settings.showSetting');
    Route::post('change-setting', 'UserController@changeSetting')->name('settings.changesetting');
    Route::get('dashboard', 'HomeController@index')->name('home.index');

    /* CMS */
    Route::get('cms/listing', 'CMSController@listing')->name('cms.listing');
    Route::get('cms', 'CMSController@index')->name('cms.index');
    Route::get('cms/{page}/edit', 'CMSController@edit')->name('cms.edit');
    Route::put('cms/{page}/edit', 'CMSController@update')->name('cms.update');

    Route::get('consumer/listing', 'ConsumerController@listing')->name('consumer.listing');
    Route::resource('consumer', 'ConsumerController');

    Route::get('enquiry/listing', 'EnquiryController@listing')->name('enquiry.listing');
    Route::resource('enquiry', 'EnquiryController');

    Route::get('property/listing', 'PropertyController@listing')->name('property.listing');
    Route::resource('property', 'PropertyController');

    Route::get('invoice/upload', 'InvoiceController@createInvoice')->name('invoice.createinvoice');
    Route::post('invoice/upload', 'InvoiceController@uploadInvoice')->name('invoice.uploadinvoice');
    Route::get('invoice/listing', 'InvoiceController@listing')->name('invoice.listing');
    Route::resource('invoice', 'InvoiceController');

    Route::get('userinvoice/upload', 'UserInvoiceController@createInvoice')->name('userinvoice.createinvoice');
    Route::post('userinvoice/upload', 'UserInvoiceController@uploadInvoice')->name('userinvoice.uploadinvoice');
    Route::get('userinvoice/listing', 'UserInvoiceController@listing')->name('userinvoice.listing');
    Route::resource('userinvoice', 'UserInvoiceController');

    Route::get('document/listing', 'DocumentController@listing')->name('document.listing');
    Route::resource('document', 'DocumentController');

    Route::post('newproperty-uploadimage', 'NewPropertyController@uploadItemImage')->name('new-property.uploadimage');
    Route::post('newproperty-removeimage', 'NewPropertyController@removeItemImage')->name('new-property.removeimage');
    Route::get('newproperty-getimage/{property_id}', 'NewPropertyController@getItemImage')->name('new-property.getimage');
    Route::get('new-property/listing', 'NewPropertyController@listing')->name('new-property.listing');
    Route::resource('new-property', 'NewPropertyController');
});


/* Unique E-mail */
Route::post('checkUniqueEmail', 'UserController@check_unique_email');

/* Required auth middleware */
Route::group(['middleware' => 'auth', 'prefix' => 'admin' ,'namespace'=> "Admin"], function () {
    Route::get('change-password', 'UserController@showChangePassword')->name('showChangePass');
    Route::post('change-password', 'UserController@changePassword')->name('changepass');

    Route::get('myprofile', 'UserController@showProfile')->name('showProfile');
    Route::post('myprofile', 'UserController@editProfile')->name('editProfile');

    Route::get('logout', 'Auth\LoginController@logout')->name('admin_logout');

    Route::post('consumer/notificationForm', 'ConsumerController@notificationForm')->name('notificationForm');

    Route::post('getuserdata', 'InvoiceController@getuserdata')->name('getuserdata');
});

routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;

//use App\Notifications\PaymentReminder;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('nocookie', 'UserController@enableCookie')->name('nocookie');
Route::get('noscript', 'UserController@noscript')->name('noscript');

// Webhook Route For Stripe Payment
Route::post(
    'stripe/webhook',
    '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook'
);

// Front End Routes
Auth::routes();

Route::get('/', 'PagesController@index')->name('home');
Route::get('new-property', 'PagesController@newproperty')->name('newproperty');
// Route::get('property-detail-page', 'PagesController@propertydetailpage')->name('property-detail-page');
Route::get('property-detail/{slug}', 'PagesController@propertydetailpage')->name('property-detail');
Route::get('about', 'PagesController@about')->name('about');
Route::get('service-overview', 'PagesController@serviceOverview')->name('overview');
Route::get('coverage', 'PagesController@coverage')->name('coverage');
Route::get('management', 'PagesController@management')->name('management');
Route::get('development', 'PagesController@development')->name('development');
Route::get('sourcing', 'PagesController@sourcing')->name('sourcing');
Route::get('contact', 'PagesController@contact')->name('contact');
Route::post('get_in_touch', 'PagesController@enquiry')->name('get_in_touch');
Route::post('property-inquiry', 'PagesController@propertyinquiry')->name('propertyinquiry');
Route::post('checkAvailableEmail', 'UserController@checkAvailableEmail');

// User Protected Routes (Portal Routes)
Route::group(['middleware' => ['user.protected','stripe.active'] ], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('properties', 'PropertyController@index')->name('properties');
    Route::post('properties', 'PropertyController@store');
    Route::get('properties/{property}', 'PropertyController@destroy');
    Route::get('invoices', 'HomeController@invoices')->name('invoices');
    
    Route::get('notifications', 'HomeController@notifications')->name('notifications');
    Route::get('settings', 'HomeController@settings')->name('settings');
    Route::post('settings', 'UserController@profile');
    Route::post('changeuserpass', 'UserController@changeuserpass')->name('changeuserpass');
    Route::get('request_callback', 'HomeController@request_callback')->name('request_callback');

    Route::get('invoices/{invoice}/pay', 'HomeController@pay')->name('invoice.pay')->where(['invoice' => '[0-9]+']);
    Route::get('invoices/{invoice}/download', 'HomeController@download')->name('download_invoice')->where(['invoice' => '[0-9]+']);
    Route::get('invoices/{invoice}/view', 'HomeController@viewPDF')->name('view_invoice')->where(['invoice' => '[0-9]+']);

    Route::get('userinvoices/{invoice}/pay', 'HomeController@payinvoice')->name('userinvoice.pay')->where(['invoice' => '[0-9]+']);
    Route::get('userinvoices/{userinvoice}/download', 'HomeController@userinvoicedownload')->name('sourcing_download_invoice')->where(['invoice' => '[0-9]+']);
    Route::get('userinvoices/{userinvoice}/view', 'HomeController@userinvoiceviewPDF')->name('sourcing_view_invoice')->where(['invoice' => '[0-9]+']);

    Route::get('documents', 'HomeController@documents')->name('documents');
});

Route::group(['middleware' => ['user.protected'] ], function () {
    /*Route::get('test', function (Request $request) {
        $request->user()->notify(new PaymentReminder());
    });*/

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('membership', 'HomeController@membership')->name('membership');
    Route::post('membership', 'HomeController@payment');
    Route::post('subscribe', 'StripeController@subscribe')->name('subscribe');

    Route::get('cards', 'CardsController@index')->name('cards');
    Route::post('cards', 'CardsController@store');
    Route::delete('cards/{id}', 'CardsController@destroy');
    Route::post('cards/default', 'CardsController@defaultCard')->name('cards.default');
});

Route::get('sms', function () {
    //dd($schedule);
    // $result = $schedule->command('reminder:send')->emailOutputTo('viral@ping2world.com');
    return Artisan::call('reminder:send');
});

// Backend Routes are stored in admin.php file
require_once 'admin.php';

app/Models/NewProperty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class NewProperty extends Model
{
   
    
    protected $fillable = ['name','price','bedroom','bathroom','livingroom','location','property_type','propery_description','latitude','longtitude','address','active','slug'];

    protected $table ='new_properties';

    public function images(){
    	return $this->hasMany(NewPropertyImage::class,'property_id','id');
    }

    public function amenities(){
    	return $this->belongsToMany(Amenities::class, 'new_properties_amenities','property_id','amenity_id');
    	
    }

    public function propertyimg(){
    	$img = $this->images->first();
    	if(isset($img->name) && Storage::exists($img->name)){
    		return Storage::url($img->name);
    	}else{
    		return asset('images/no-property-image.png');
    	}
    }

    

}

resources/views/pages/new-property/list.blade.php
@extends('layouts.app')
@section('title') {{$headTitle}} @endsection

@section('breadcrumb')
{!! Breadcrumbs::render('new_property') !!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-calculator font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">{{$headTitle}}</span>
                </div>
                <div class="tools">
                </div>
                <div class="actions">
                    @if (in_array('add', $permissions))
                        <a href="{{route('new-property.create')}}" class="btn btn-circle green tooltips" data-container="body" data-placement="top" data-original-title="New Property"> Add New Property
                            <i class="fa fa-plus"></i>
                        </a>
                    @endif
                </div>
            </div>
            @if (in_array('delete', $permissions))
                <a href="{{ route('new-property.destroy',0) }}" name="del_select" id="del_select" class="btn btn-sm btn-danger btn-circle delete_all_link" style="margin-left: 20px;">Delete Selected
                    <i class="fa fa-trash  fa-lg"></i>  
                </a>
            @endif
            <div class="portlet-body">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover" id="table_DT">
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
    $(function(){
        var table = $('#table_DT');

        oTable = table.dataTable({
            "processing": true,
            "serverSide": true,
            "language": {
                "aria": {
                    "sortAscending": ": click to sort column ascending",
                    "sortDescending": ": click to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "_MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },
            "columns": [
                @if (in_array('delete', $permissions))
                    { "title": "<input type='checkbox' class='all_select'>" ,"data": "checkbox","width":"3%",searchble: false, sortable:false},
                @endif
                { "title": "Name" ,"data": "name"},
                { "title": "Price" ,"data": "price"},
                { "title": "Location" ,"data": "location"},
                { "title": "Property Type" ,"data": "property_type"},
                @if (in_array('edit', $permissions))
                    { "title": "Status" ,"data": "active", searchble: false },
                @endif
                @if (in_array('view', $permissions) || in_array('edit', $permissions) || in_array('delete', $permissions))
                    { "title": "Action" ,"data": "action", searchble: false, sortable:false }
                @endif
            ],
            responsive: false,
            "order": [
                @if (in_array('delete', $permissions))
                    [1, 'asc']
                @else
                    [0, 'asc']
                @endif
            ],
            "lengthMenu": [
                [10, 20, 50,100],
                [10, 20, 50,100]
            ],
            "pageLength": 10,
            "ajax": {
                "url": "{{route('new-property.listing')}}", // ajax source
            },
            drawCallback: function( oSettings ) {
                $('.make-switch').bootstrapSwitch();
                $('.make-switch').bootstrapSwitch('onColor', 'success');
                $('.make-switch').bootstrapSwitch('offColor', 'danger');
            },
            "dom": "<'row' <'col-md-12'>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
        });
    });
</script>
@endpush