routes/admin.php
<?php

Route::group(['prefix' => 'admin',  'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::get('', 'Auth\LoginController@showLoginForm');
});

/* Required auth and permission middleware */
Route::group(['middleware' => ['auth', 'permission'],'prefix'=>'admin','namespace'=>"Admin"], function () {

    /*General settings */
    Route::get('settings', 'UserController@showSetting')->name('settings.showSetting');
    Route::post('change-setting', 'UserController@changeSetting')->name('settings.changesetting');
    Route::get('dashboard', 'HomeController@index')->name('home.index');

    /* CMS */
    Route::get('cms/listing', 'CMSController@listing')->name('cms.listing');
    Route::get('cms', 'CMSController@index')->name('cms.index');
    Route::get('cms/{page}/edit', 'CMSController@edit')->name('cms.edit');
    Route::put('cms/{page}/edit', 'CMSController@update')->name('cms.update');

    Route::get('consumer/listing', 'ConsumerController@listing')->name('consumer.listing');
    Route::resource('consumer', 'ConsumerController');

    Route::get('enquiry/listing', 'EnquiryController@listing')->name('enquiry.listing');
    Route::resource('enquiry', 'EnquiryController');

    Route::get('property/listing', 'PropertyController@listing')->name('property.listing');
    Route::resource('property', 'PropertyController');

    Route::get('invoice/upload', 'InvoiceController@createInvoice')->name('invoice.createinvoice');
    Route::post('invoice/upload', 'InvoiceController@uploadInvoice')->name('invoice.uploadinvoice');
    Route::get('invoice/listing', 'InvoiceController@listing')->name('invoice.listing');
    Route::resource('invoice', 'InvoiceController');

    Route::get('userinvoice/upload', 'UserInvoiceController@createInvoice')->name('userinvoice.createinvoice');
    Route::post('userinvoice/upload', 'UserInvoiceController@uploadInvoice')->name('userinvoice.uploadinvoice');
    Route::get('userinvoice/listing', 'UserInvoiceController@listing')->name('userinvoice.listing');
    Route::resource('userinvoice', 'UserInvoiceController');

    Route::get('document/listing', 'DocumentController@listing')->name('document.listing');
    Route::resource('document', 'DocumentController');

    Route::post('newproperty-uploadimage', 'NewPropertyController@uploadItemImage')->name('new-property.uploadimage');
    Route::post('newproperty-removeimage', 'NewPropertyController@removeItemImage')->name('new-property.removeimage');
    Route::get('newproperty-getimage/{property_id}', 'NewPropertyController@getItemImage')->name('new-property.getimage');
    Route::get('new-property/listing', 'NewPropertyController@listing')->name('new-property.listing');
    Route::resource('new-property', 'NewPropertyController');
});


/* Unique E-mail */
Route::post('checkUniqueEmail', 'UserController@check_unique_email');

/* Required auth middleware */
Route::group(['middleware' => 'auth', 'prefix' => 'admin' ,'namespace'=> "Admin"], function () {
    Route::get('change-password', 'UserController@showChangePassword')->name('showChangePass');
    Route::post('change-password', 'UserController@changePassword')->name('changepass');

    Route::get('myprofile', 'UserController@showProfile')->name('showProfile');
    Route::post('myprofile', 'UserController@editProfile')->name('editProfile');

    Route::get('logout', 'Auth\LoginController@logout')->name('admin_logout');

    Route::post('consumer/notificationForm', 'ConsumerController@notificationForm')->name('notificationForm');

    Route::post('getuserdata', 'InvoiceController@getuserdata')->name('getuserdata');
});

routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;

//use App\Notifications\PaymentReminder;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('nocookie', 'UserController@enableCookie')->name('nocookie');
Route::get('noscript', 'UserController@noscript')->name('noscript');

// Webhook Route For Stripe Payment
Route::post(
    'stripe/webhook',
    '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook'
);

// Front End Routes
Auth::routes();

Route::get('/', 'PagesController@index')->name('home');
Route::get('new-property', 'PagesController@newproperty')->name('newproperty');
// Route::get('property-detail-page', 'PagesController@propertydetailpage')->name('property-detail-page');
Route::get('property-detail/{slug}', 'PagesController@propertydetailpage')->name('property-detail');
Route::get('about', 'PagesController@about')->name('about');
Route::get('service-overview', 'PagesController@serviceOverview')->name('overview');
Route::get('coverage', 'PagesController@coverage')->name('coverage');
Route::get('management', 'PagesController@management')->name('management');
Route::get('development', 'PagesController@development')->name('development');
Route::get('sourcing', 'PagesController@sourcing')->name('sourcing');
Route::get('contact', 'PagesController@contact')->name('contact');
Route::post('get_in_touch', 'PagesController@enquiry')->name('get_in_touch');
Route::post('property-inquiry', 'PagesController@propertyinquiry')->name('propertyinquiry');
Route::post('checkAvailableEmail', 'UserController@checkAvailableEmail');

// User Protected Routes (Portal Routes)
Route::group(['middleware' => ['user.protected','stripe.active'] ], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('properties', 'PropertyController@index')->name('properties');
    Route::post('properties', 'PropertyController@store');
    Route::get('properties/{property}', 'PropertyController@destroy');
    Route::get('invoices', 'HomeController@invoices')->name('invoices');
    
    Route::get('notifications', 'HomeController@notifications')->name('notifications');
    Route::get('settings', 'HomeController@settings')->name('settings');
    Route::post('settings', 'UserController@profile');
    Route::post('changeuserpass', 'UserController@changeuserpass')->name('changeuserpass');
    Route::get('request_callback', 'HomeController@request_callback')->name('request_callback');

    Route::get('invoices/{invoice}/pay', 'HomeController@pay')->name('invoice.pay')->where(['invoice' => '[0-9]+']);
    Route::get('invoices/{invoice}/download', 'HomeController@download')->name('download_invoice')->where(['invoice' => '[0-9]+']);
    Route::get('invoices/{invoice}/view', 'HomeController@viewPDF')->name('view_invoice')->where(['invoice' => '[0-9]+']);

    Route::get('userinvoices/{invoice}/pay', 'HomeController@payinvoice')->name('userinvoice.pay')->where(['invoice' => '[0-9]+']);
    Route::get('userinvoices/{userinvoice}/download', 'HomeController@userinvoicedownload')->name('sourcing_download_invoice')->where(['invoice' => '[0-9]+']);
    Route::get('userinvoices/{userinvoice}/view', 'HomeController@userinvoiceviewPDF')->name('sourcing_view_invoice')->where(['invoice' => '[0-9]+']);

    Route::get('documents', 'HomeController@documents')->name('documents');
});

Route::group(['middleware' => ['user.protected'] ], function () {
    /*Route::get('test', function (Request $request) {
        $request->user()->notify(new PaymentReminder());
    });*/

    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('membership', 'HomeController@membership')->name('membership');
    Route::post('membership', 'HomeController@payment');
    Route::post('subscribe', 'StripeController@subscribe')->name('subscribe');

    Route::get('cards', 'CardsController@index')->name('cards');
    Route::post('cards', 'CardsController@store');
    Route::delete('cards/{id}', 'CardsController@destroy');
    Route::post('cards/default', 'CardsController@defaultCard')->name('cards.default');
});

Route::get('sms', function () {
    //dd($schedule);
    // $result = $schedule->command('reminder:send')->emailOutputTo('viral@ping2world.com');
    return Artisan::call('reminder:send');
});

// Backend Routes are stored in admin.php file
require_once 'admin.php';

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Document extends Model
{
    use SoftDeletes;

    protected $fillable = ['title','path','size','active','user_id'];
}

app/Http/Controllers/Admin/DocumentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Document;
use App\User;
use Illuminate\Http\Request;
use Storage;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.document.list')->with('headTitle', 'Documents');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::where('user_type', 'user')->where('active', 1)->get();
        return view('pages.document.add',compact('users'))->with('headTitle', 'Document');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required',
            'user_id' => 'required',
            'document' => 'sometimes|mimes:jpg,jpeg,bmp,png,doc,docx,csv,rtf,xlsx,xls,txt,pdf,zip',
        ];
        $this->validateForm($request->all(), $rules);
        $user_id = null;
        if(!empty($request->user_id)){
            $user_id = implode(',',$request->user_id);
        }
        $document = new Document;
        $document->user_id = $user_id ? $user_id : null;
        $document->title = $request->title;
        $document->path = $request->file('document')->store('document');
        $document->size = $request->file('document')->getSize();
        $document->save();
        
        flash('Document added successfully.')->success();
        return redirect()->route('document.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        return view('pages.document.view',compact('document'))->with('headTitle', 'View Documents');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        $users = User::where('user_type', 'user')->where('active', 1)->get();
        return view('pages.document.edit',compact('document','users'))->with('headTitle', 'Edit Documents');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if (!empty($request->action) && $request->action == 'change_status') {
            $content  = ['status' => 204, 'message' => "something went wrong"];
            $doc = Document::find($id);
            if ($doc) {
                $doc->active = $request->value;
                if ($doc->save()) {
                    $content['status']  = 200;
                    $content['message'] = "Status updated successfully.";
                }
            }
            return response()->json($content);
        } else {
            $rules = [
                'title'    => 'required',
                'user_id'    => 'required',

                'document' => 'sometimes|mimes:jpg,jpeg,bmp,png,doc,docx,csv,rtf,xlsx,xls,txt,pdf,zip',
            ];
            $this->validateForm($request->all(), $rules);

            $document = Document::find($id);

            if ($request->hasFile('document')) {
                Storage::delete($document->path);
                $document->path = $request->file('document')->store('document');
                $document->size = $request->file('document')->getSize();
            }

            if ($document) {
                $user_id = null;
                if(!empty($request->user_id)){
                    $user_id = implode(',',$request->user_id);
                }
                $document->user_id = $user_id ? $user_id : null;
                $document->title = $request->title;
                $document->save();

                flash('Document updated successfully.')->success();
                return redirect()->route('document.index');
            } else {
                abort(404);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (!empty($request->action) && $request->action == 'delete_all') {
            $content = ['status' => 204, 'message' => "something went wrong"];
            
            $documents = Document::whereIn('id',explode(',',$request->ids))->get();

            foreach ($documents as $key => $doc) {
                Storage::delete($doc->path);
                $doc->delete();
            }
            
            $content['status']  = 200;
            $content['message'] = "Documents deleted successfully.";
            return response()->json($content);
        } else {
            $document = Document::find($id);
            Storage::delete($document->path);
            $document->delete();

            if (request()->ajax()) {
                $content = array('status' => 200, 'message' => "Document deleted successfully.");
                return response()->json($content);
            } else {
                flash('Document deleted successfully.')->success();
                return redirect()->route('document.index');
            }
        }
    }

    public function listing(Request $request)
    {
        extract($this->DTFilters($request->all()));
        $documents = Document::where('id','<>',0);

            if ($search != '') {
                $documents->where(function ($query) use ($search) {
                    $query->where("reference", "like", "%{$search}%");
                });
            }                            
       
        $count = $documents->count();

        $records["recordsTotal"] = $count;
        $records["recordsFiltered"] = $count;
        $records['data'] = array();
        $documents = $documents->orderBy($sort_column, $sort_order)->offset($offset)->limit($limit)->get();

        foreach ($documents as $doc) {

            $params = array(
                'url'       => route('document.update', $doc->id),
                'checked'   => ($doc->active == 1) ? "checked" : "",
                'getaction' => '',
                'class'     => '',
            );

            $records['data'][] = [
                'checkbox'=>view('shared.checkbox')->with('id', $doc->id)->render(),
                'title'=>$doc->title,
                'size'=>formatBytes($doc->size),
                'active' => view('shared.switch')->with(['params' => $params, 'id' => $doc->id])->render(),
                'action'=>view('shared.actions')->with('id', $doc->id)->render(),
            ];
        }
        return $records;
    }
}

resources/views/pages/document/add.blade.php
@extends('layouts.app')
@section('title') {{$headTitle}} @endsection

@section('breadcrumb')
{!! Breadcrumbs::render('add_document') !!}
@endsection
@push('page_css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.multiselect.css') }}">
@endpush
@section('content')
 <div class="row ">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">{{$headTitle}}</span>
                </div>
            </div>
            <div class="portlet-body">
                <form id="frmdocument" class="form-horizontal" role="form" method="POST" action="{{ route('document.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    
                    <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }} user_id">
                        <label for="user_id" class="col-md-2 control-label">Select Counsumer{!! $mend_sign !!}</label>
                        <div class="col-md-4">
                            <div class="input-icon">
                                <select name="user_id[]" id="user_id"  multiple='multiple' class="3col active"  data-error-container="#user_id-error">
                                    @if($users)
                                        @foreach($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->first_name.' '.$user->last_name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if ($errors->has('user_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user_id') }}</strong>
                                    </span>
                                @endif
                                <span id="user_id-error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title" class="col-md-2 control-label">Title{!! $mend_sign !!}</label>
                        <div class="col-md-4">
                            <div class="input-icon">
                                <i class="fa fa-header"></i>
                                <input type="text" placeholder="Enter Title" name="title" id="title" class="form-control" value="{{old('title','')}}" maxlength="150" />
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                   
                    <div class="form-group{{ $errors->has('document') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-2 control-label">Document{!! $mend_sign !!}</label>
                        <div class="col-md-4">
                            <div class="input-icon">
                                <i class="fa fa-upload"></i>
                                <input type="file" name="document" id="document" class="form-control" />
                                @if ($errors->has('document'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('document') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn green">Submit</button>
                            <a href="{{route('document.index')}}" class="btn red">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- End: SAMPLE FORM PORTLET -->
    </div>
</div>
@endsection

@push('scripts')
<script  src="{{ asset('js/jquery.multiselect.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#user_id').multiselect({
        columns: 1,
        search: true,
        selectAll : true,
        placeholder: 'Select Counsumer',
    });
    $('body').on('change', '#user_id', function(){
        $('#user_id').valid();
    }); 
    $("#frmdocument").validate({
        ignore:[],
        rules: {
            title:{ 
                required:true 
            },
            document:{
                required:true,
                // accept:'pdf,jpge,jpg,png,doc,docx,txt'
            },
            'user_id[]':{ 
                required:true 
            },
            
        },
        messages: {
            title:{
                required:"@lang('validation.required',['attribute'=>'title'])"
            },
            'user_id[]':{
                required:"@lang('validation.required',['attribute'=>'user'])"
            },
            document:{
                required:"@lang('validation.required',['attribute'=>'document'])",
                accept:"@lang('validation.mimetypes',['attribute'=>'document','value'=>' .pdf, .jpge, .jpg, .png, .doc, .docx, .txt, .zip'])"
            }
        },
        errorClass: 'help-block',
        errorElement: 'span',
        highlight: function (element) {
           $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function (element) {
           $(element).closest('.form-group').removeClass('has-error');
        },
        errorPlacement: function (error, element) {
            if (element.attr("type") == "radio") {
                  error.appendTo('.a');
            }else{
                if (element.attr("data-error-container")) {
                    error.appendTo(element.attr("data-error-container"));
                } else {
                    error.insertAfter(element);
                }
            }
        }
    });
    $(document).on('submit','#frmdocument',function(){
        if($("#frmdocument").valid()){
            if ($(this).valid()) {
                addOverlay();
                $("input[type=submit], input[type=button], button[type=submit]").prop("disabled", "disabled");
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    });
});

</script>

@endpush

resources/views/pages/document/list.blade.php
@extends('layouts.app')
@section('title') {{$headTitle}} @endsection

@section('breadcrumb')
{!! Breadcrumbs::render('document') !!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-calculator font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">{{$headTitle}}</span>
                </div>
                <div class="tools">
                </div>
                <div class="actions">
                    @if (in_array('add', $permissions))
                        <a href="{{route('document.create')}}" class="btn btn-circle green tooltips" data-container="body" data-placement="top" data-original-title="Document"> Add Document
                            <i class="fa fa-plus"></i>
                        </a>
                    @endif
                </div>
            </div>
            @if (in_array('delete', $permissions))
                <a href="{{ route('document.destroy',0) }}" name="del_select" id="del_select" class="btn btn-sm btn-danger btn-circle delete_all_link" style="margin-left: 20px;">Delete Selected
                    <i class="fa fa-trash  fa-lg"></i>  
                </a>
            @endif
            <div class="portlet-body">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover" id="table_DT">
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
    $(function(){
        var table = $('#table_DT');

        oTable = table.dataTable({
            "processing": true,
            "serverSide": true,
            "language": {
                "aria": {
                    "sortAscending": ": click to sort column ascending",
                    "sortDescending": ": click to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "_MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },
            "columns": [
                @if (in_array('delete', $permissions))
                    { "title": "<input type='checkbox' class='all_select'>" ,"data": "checkbox","width":"3%",searchble: false, sortable:false},
                @endif
                { "title": "Title" ,"data": "title"},
                { "title": "Size" ,"data": "size"},
                @if (in_array('edit', $permissions))
                    { "title": "Status" ,"data": "active", searchble: false },
                @endif
                @if (in_array('view', $permissions) || in_array('edit', $permissions) || in_array('delete', $permissions))
                    { "title": "Action" ,"data": "action", searchble: false, sortable:false }
                @endif
            ],
            responsive: false,
            "order": [
                @if (in_array('delete', $permissions))
                    [1, 'asc']
                @else
                    [0, 'asc']
                @endif
            ],
            "lengthMenu": [
                [10, 20, 50,100],
                [10, 20, 50,100]
            ],
            "pageLength": 10,
            "ajax": {
                "url": "{{route('document.listing')}}", // ajax source
            },
            drawCallback: function( oSettings ) {
                $('.make-switch').bootstrapSwitch();
                $('.make-switch').bootstrapSwitch('onColor', 'success');
                $('.make-switch').bootstrapSwitch('offColor', 'danger');
            },
            "dom": "<'row' <'col-md-12'>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
        });
    });
</script>
@endpush